### ISSUE TITLE
unclear which icinga role is used

### ISSUE THREAD

**Issue by brucellino** [rciam/rciam-deploy#271]
In `icingaagents.yml` reference is made to a dependency (`role: icinga`). This is not present in the repo and not declared anywhere.

I'm assuming a role is being used from Galaxy - can you specify which one?

**Comment by NicolasLiampotis** [comment]
RCIAM does not rely on a specific monitoring tool, so it's cleaner to move GRNET-specific playbooks to a different repository. The `icingaagents.yml` playbook has been removed with commit 1abfe64

🙏  Thanks for bringing this up, Bruce!
